# This is a basic workflow that is manually triggered

name: Postman workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
      branches:
          - master
  schedule:
    - cron:  '00 10 * * *'


jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
            node-version: '12.x'
            
      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra
         
      - name: Make Directory for results
        run: mkdir -p testResults
        
      - name: Run POSTMAN collection
        run: |
         newman run ./postman/rest_assured_demo_postman_collection.json -e ./postman/rest_assured_demo_postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

    # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with: 
         name: RunReports
         path: testResults
